export const movieData = [
  {
    title: "The Shawshank Redemption",
    reviews: [],
    imdbRating: 9.3,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Godfather",
    reviews: [],
    imdbRating: 9.2,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Dark Knight",
    reviews: [],
    imdbRating: 9.0,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Pulp Fiction",
    reviews: [],
    imdbRating: 8.9,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    reviews: [],
    imdbRating: 8.9,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Schindler's List",
    reviews: [],
    imdbRating: 8.9,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Inception",
    reviews: [],
    imdbRating: 8.8,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Fight Club",
    reviews: [],
    imdbRating: 8.8,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Forrest Gump",
    reviews: [],
    imdbRating: 8.8,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Matrix",
    reviews: [],
    imdbRating: 8.7,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Goodfellas",
    reviews: [],
    imdbRating: 8.7,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Silence of the Lambs",
    reviews: [],
    imdbRating: 8.6,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    reviews: [],
    imdbRating: 8.8,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Usual Suspects",
    reviews: [],
    imdbRating: 8.5,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Se7en",
    reviews: [],
    imdbRating: 8.6,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Green Mile",
    reviews: [],
    imdbRating: 8.6,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    reviews: [],
    imdbRating: 8.7,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "Saving Private Ryan",
    reviews: [],
    imdbRating: 8.6,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Pianist",
    reviews: [],
    imdbRating: 8.5,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
  {
    title: "The Departed",
    reviews: [],
    imdbRating: 8.5,
    img: "https://placehold.co/400X600",
    stars: 0,
  },
];
